export const indicators = [
  { code: 'I01', name: 'Suka matematika', group: 'Logika & Teknologi', description: 'Nyaman dengan hitungan, rumus, dan pola numerik.' },
  { code: 'I02', name: 'Suka logika', group: 'Logika & Teknologi', description: 'Menikmati proses berpikir runtut dan analitis.' },
  { code: 'I03', name: 'Tertarik teknologi', group: 'Logika & Teknologi', description: 'Punya rasa ingin tahu terhadap aplikasi dan sistem digital.' },
  { code: 'I04', name: 'Suka pemrograman', group: 'Logika & Teknologi', description: 'Tertarik membuat aplikasi, website, atau mempelajari coding.' },
  { code: 'I15', name: 'Suka memecahkan masalah', group: 'Logika & Teknologi', description: 'Tertantang mencari solusi dari persoalan yang rumit.' },
  { code: 'I36', name: 'Tertarik keamanan digital', group: 'Logika & Teknologi', description: 'Suka memahami jaringan, proteksi data, dan risiko siber.' },
  { code: 'I05', name: 'Suka analisis data', group: 'Data & Keuangan', description: 'Senang membaca pola dari angka, grafik, dan informasi.' },
  { code: 'I07', name: 'Teliti menghitung', group: 'Data & Keuangan', description: 'Terbiasa cermat saat mengolah angka atau dokumen.' },
  { code: 'I08', name: 'Suka angka', group: 'Data & Keuangan', description: 'Merasa nyaman dengan data kuantitatif dan laporan numerik.' },
  { code: 'I19', name: 'Suka riset', group: 'Data & Keuangan', description: 'Senang menggali informasi dan membandingkan referensi.' },
  { code: 'I20', name: 'Suka pekerjaan terstruktur', group: 'Data & Keuangan', description: 'Nyaman dengan aturan kerja yang rapi dan sistematis.' },
  { code: 'I31', name: 'Tertarik ekonomi dan keuangan', group: 'Data & Keuangan', description: 'Suka memahami uang, pasar, investasi, dan keputusan ekonomi.' },
  { code: 'I06', name: 'Suka bisnis', group: 'Bisnis & Organisasi', description: 'Tertarik pada strategi usaha, pemasaran, dan pengelolaan organisasi.' },
  { code: 'I16', name: 'Suka kerja tim', group: 'Bisnis & Organisasi', description: 'Nyaman berkolaborasi untuk mencapai target bersama.' },
  { code: 'I17', name: 'Suka perencanaan', group: 'Bisnis & Organisasi', description: 'Tertarik menyusun strategi, jadwal, dan tahapan kerja.' },
  { code: 'I18', name: 'Suka organisasi', group: 'Bisnis & Organisasi', description: 'Senang mengelola kegiatan, orang, dan agenda.' },
  { code: 'I11', name: 'Suka komunikasi', group: 'Komunikasi & Sosial', description: 'Senang menyampaikan ide dan berinteraksi dengan orang lain.' },
  { code: 'I12', name: 'Percaya diri berbicara', group: 'Komunikasi & Sosial', description: 'Nyaman presentasi, public speaking, atau berdiskusi.' },
  { code: 'I13', name: 'Suka membantu orang', group: 'Komunikasi & Sosial', description: 'Peka terhadap kebutuhan orang lain dan senang memberi dukungan.' },
  { code: 'I14', name: 'Tertarik perilaku manusia', group: 'Komunikasi & Sosial', description: 'Penasaran pada pola pikir, emosi, dan kebiasaan manusia.' },
  { code: 'I24', name: 'Tertarik hukum dan keadilan', group: 'Komunikasi & Sosial', description: 'Peduli pada aturan, argumen, hak, dan penyelesaian konflik.' },
  { code: 'I25', name: 'Suka menulis', group: 'Komunikasi & Sosial', description: 'Senang menyusun gagasan, cerita, artikel, atau dokumen tertulis.' },
  { code: 'I26', name: 'Suka bahasa asing', group: 'Komunikasi & Sosial', description: 'Tertarik memahami bahasa, budaya, dan komunikasi lintas negara.' },
  { code: 'I27', name: 'Suka mengajar', group: 'Komunikasi & Sosial', description: 'Senang menjelaskan materi dan membantu orang lain belajar.' },
  { code: 'I34', name: 'Peduli isu sosial', group: 'Komunikasi & Sosial', description: 'Tertarik pada masyarakat, kebijakan publik, dan perubahan sosial.' },
  { code: 'I09', name: 'Kreatif', group: 'Kreatif & Ruang', description: 'Senang menghasilkan ide baru dan solusi unik.' },
  { code: 'I10', name: 'Suka desain visual', group: 'Kreatif & Ruang', description: 'Tertarik pada ilustrasi, tata letak, warna, dan visual branding.' },
  { code: 'I29', name: 'Suka bangunan dan ruang', group: 'Kreatif & Ruang', description: 'Tertarik pada desain bangunan, tata ruang, dan konstruksi.' },
  { code: 'I32', name: 'Suka media kreatif', group: 'Kreatif & Ruang', description: 'Senang membuat konten, foto, video, audio, atau karya digital.' },
  { code: 'I35', name: 'Suka peta dan wilayah', group: 'Kreatif & Ruang', description: 'Tertarik membaca wilayah, kota, transportasi, dan data spasial.' },
  { code: 'I21', name: 'Tertarik biologi dan kesehatan', group: 'Kesehatan & Sains', description: 'Senang mempelajari tubuh manusia, makhluk hidup, dan kesehatan.' },
  { code: 'I22', name: 'Suka merawat pasien', group: 'Kesehatan & Sains', description: 'Peduli terhadap perawatan dan keselamatan orang lain.' },
  { code: 'I23', name: 'Suka kimia dan laboratorium', group: 'Kesehatan & Sains', description: 'Tertarik pada eksperimen, obat, bahan, dan prosedur laboratorium.' },
  { code: 'I28', name: 'Tertarik mesin dan alat', group: 'Teknik & Lingkungan', description: 'Ingin memahami cara kerja mesin, alat produksi, dan sistem mekanik.' },
  { code: 'I30', name: 'Peduli lingkungan', group: 'Teknik & Lingkungan', description: 'Tertarik pada isu alam, keberlanjutan, dan pengelolaan lingkungan.' },
  { code: 'I33', name: 'Tertarik pertanian dan pangan', group: 'Teknik & Lingkungan', description: 'Peduli pada produksi pangan, agribisnis, dan sumber daya hayati.' },
];

export const majors = [
  { code: 'J01', name: 'Teknik Informatika', description: 'Fokus pada algoritma, pemrograman, rekayasa perangkat lunak, dan sistem komputasi.', careers: 'Software engineer, backend developer, mobile developer, data engineer.' },
  { code: 'J02', name: 'Sistem Informasi', description: 'Menggabungkan teknologi informasi, proses bisnis, analisis kebutuhan, dan pengelolaan sistem organisasi.', careers: 'Business analyst, system analyst, IT consultant, product analyst.' },
  { code: 'J03', name: 'Akuntansi', description: 'Mempelajari pencatatan, audit, pajak, analisis, dan pelaporan keuangan.', careers: 'Akuntan, auditor, tax staff, financial analyst.' },
  { code: 'J04', name: 'Manajemen', description: 'Mempelajari strategi bisnis, pemasaran, sumber daya manusia, operasional, dan kewirausahaan.', careers: 'Management trainee, HR officer, marketing executive, entrepreneur.' },
  { code: 'J05', name: 'Ilmu Komunikasi', description: 'Mempelajari komunikasi massa, public relations, media, konten, dan strategi komunikasi.', careers: 'Public relations, content strategist, broadcaster, media planner.' },
  { code: 'J06', name: 'Psikologi', description: 'Mempelajari perilaku, emosi, proses mental, asesmen, dan interaksi manusia.', careers: 'HR specialist, counselor assistant, researcher, assessor.' },
  { code: 'J07', name: 'Desain Komunikasi Visual', description: 'Fokus pada desain grafis, identitas visual, ilustrasi, multimedia, dan pengalaman pengguna.', careers: 'Graphic designer, UI designer, illustrator, creative designer.' },
  { code: 'J08', name: 'Teknik Industri', description: 'Berfokus pada optimasi sistem kerja, efisiensi proses, manajemen produksi, dan rantai pasok.', careers: 'Industrial engineer, production planner, quality control, supply chain analyst.' },
  { code: 'J09', name: 'Kedokteran', description: 'Mempelajari ilmu biomedis, diagnosis, pencegahan, dan penanganan kesehatan manusia.', careers: 'Dokter umum, peneliti klinis, tenaga kesehatan, medical officer.' },
  { code: 'J10', name: 'Keperawatan', description: 'Mempelajari perawatan pasien, komunikasi terapeutik, keselamatan pasien, dan pelayanan kesehatan.', careers: 'Perawat, caregiver profesional, edukator kesehatan, case manager.' },
  { code: 'J11', name: 'Farmasi', description: 'Mempelajari obat, formulasi, farmakologi, kimia farmasi, dan layanan kefarmasian.', careers: 'Apoteker, quality assurance farmasi, regulatory affairs, peneliti obat.' },
  { code: 'J12', name: 'Ilmu Hukum', description: 'Mempelajari hukum pidana, perdata, tata negara, kontrak, dan argumentasi hukum.', careers: 'Legal officer, advokat, notaris, compliance staff.' },
  { code: 'J13', name: 'Pendidikan Guru', description: 'Mempelajari pedagogi, strategi pembelajaran, asesmen, dan pengembangan peserta didik.', careers: 'Guru, tutor, pengembang kurikulum, fasilitator pendidikan.' },
  { code: 'J14', name: 'Arsitektur', description: 'Mempelajari perancangan bangunan, estetika ruang, teknologi konstruksi, dan konteks lingkungan.', careers: 'Arsitek, drafter, urban designer, konsultan desain bangunan.' },
  { code: 'J15', name: 'Teknik Mesin', description: 'Mempelajari mekanika, material, manufaktur, energi, dan perancangan mesin.', careers: 'Mechanical engineer, maintenance engineer, production engineer, design engineer.' },
  { code: 'J16', name: 'Agribisnis', description: 'Mempelajari bisnis pertanian, rantai pasok pangan, pemasaran komoditas, dan kewirausahaan agrikultur.', careers: 'Agribusiness analyst, entrepreneur pangan, supply chain staff, penyuluh agribisnis.' },
  { code: 'J17', name: 'Ilmu Lingkungan', description: 'Mempelajari ekologi, konservasi, pencemaran, kebijakan lingkungan, dan keberlanjutan.', careers: 'Environmental officer, sustainability analyst, konsultan lingkungan, peneliti.' },
  { code: 'J18', name: 'Hubungan Internasional', description: 'Mempelajari politik global, diplomasi, ekonomi internasional, budaya, dan isu lintas negara.', careers: 'Diplomat, analis kebijakan, NGO officer, international relations staff.' },
  { code: 'J19', name: 'Statistika', description: 'Mempelajari probabilitas, pemodelan data, survei, inferensi statistik, dan visualisasi data.', careers: 'Data analyst, statistician, risk analyst, market researcher.' },
  { code: 'J20', name: 'Teknik Sipil', description: 'Mempelajari struktur, konstruksi, transportasi, geoteknik, dan manajemen infrastruktur.', careers: 'Civil engineer, site engineer, structural engineer, project estimator.' },
  { code: 'J21', name: 'Teknik Elektro', description: 'Mempelajari sistem kelistrikan, elektronika, telekomunikasi, kontrol, dan energi.', careers: 'Electrical engineer, control engineer, telecommunication engineer, power system analyst.' },
  { code: 'J22', name: 'Teknik Kimia', description: 'Mempelajari proses industri, reaksi kimia, pengolahan bahan, dan teknologi produksi.', careers: 'Process engineer, production engineer, quality control, research and development staff.' },
  { code: 'J23', name: 'Ilmu Gizi', description: 'Mempelajari nutrisi, kesehatan masyarakat, pola makan, dan perencanaan gizi.', careers: 'Nutritionist, konsultan gizi, food service planner, edukator kesehatan.' },
  { code: 'J24', name: 'Kesehatan Masyarakat', description: 'Mempelajari promosi kesehatan, epidemiologi, kebijakan kesehatan, dan pencegahan penyakit.', careers: 'Health promoter, epidemiology staff, public health officer, program evaluator.' },
  { code: 'J25', name: 'Administrasi Bisnis', description: 'Mempelajari pengelolaan bisnis, operasional, pemasaran, layanan, dan administrasi organisasi.', careers: 'Business development staff, operations officer, account executive, administrative manager.' },
  { code: 'J26', name: 'Ekonomi Pembangunan', description: 'Mempelajari ekonomi makro, kebijakan publik, pembangunan wilayah, dan analisis ekonomi.', careers: 'Economic analyst, policy analyst, researcher, planning officer.' },
  { code: 'J27', name: 'Sastra Inggris', description: 'Mempelajari bahasa, sastra, budaya, penerjemahan, dan komunikasi lintas budaya.', careers: 'Translator, interpreter, content writer, language specialist.' },
  { code: 'J28', name: 'Ilmu Politik', description: 'Mempelajari pemerintahan, kebijakan publik, partai politik, demokrasi, dan analisis kekuasaan.', careers: 'Policy analyst, political researcher, campaign staff, public affairs officer.' },
  { code: 'J29', name: 'Perencanaan Wilayah dan Kota', description: 'Mempelajari tata ruang, transportasi, pengembangan kota, pemetaan, dan kebijakan wilayah.', careers: 'Urban planner, regional planner, GIS analyst, transport planner.' },
  { code: 'J30', name: 'Teknik Lingkungan', description: 'Mempelajari pengelolaan limbah, air, pencemaran, energi berkelanjutan, dan teknologi lingkungan.', careers: 'Environmental engineer, waste management officer, sustainability consultant, water treatment engineer.' },
];

export const campuses = [
  { name: 'Universitas Indonesia', city: 'Depok', province: 'Jawa Barat', type: 'PTN', website: 'https://www.ui.ac.id', majors: ['J01', 'J02', 'J03', 'J04', 'J05', 'J06', 'J09', 'J10', 'J11', 'J12', 'J18'] },
  { name: 'Institut Teknologi Bandung', city: 'Bandung', province: 'Jawa Barat', type: 'PTN', website: 'https://www.itb.ac.id', majors: ['J01', 'J07', 'J08', 'J14', 'J15', 'J17', 'J19', 'J20'] },
  { name: 'Universitas Gadjah Mada', city: 'Yogyakarta', province: 'DI Yogyakarta', type: 'PTN', website: 'https://ugm.ac.id', majors: ['J01', 'J03', 'J04', 'J05', 'J06', 'J09', 'J10', 'J11', 'J12', 'J14', 'J15', 'J16', 'J17', 'J18', 'J20'] },
  { name: 'Institut Teknologi Sepuluh Nopember', city: 'Surabaya', province: 'Jawa Timur', type: 'PTN', website: 'https://www.its.ac.id', majors: ['J01', 'J02', 'J08', 'J14', 'J15', 'J20'] },
  { name: 'IPB University', city: 'Bogor', province: 'Jawa Barat', type: 'PTN', website: 'https://ipb.ac.id', majors: ['J03', 'J04', 'J16', 'J17', 'J19'] },
  { name: 'Universitas Airlangga', city: 'Surabaya', province: 'Jawa Timur', type: 'PTN', website: 'https://unair.ac.id', majors: ['J03', 'J04', 'J05', 'J06', 'J09', 'J10', 'J11', 'J12', 'J18'] },
  { name: 'Universitas Padjadjaran', city: 'Sumedang', province: 'Jawa Barat', type: 'PTN', website: 'https://www.unpad.ac.id', majors: ['J03', 'J04', 'J05', 'J06', 'J09', 'J10', 'J11', 'J12', 'J18'] },
  { name: 'Universitas Diponegoro', city: 'Semarang', province: 'Jawa Tengah', type: 'PTN', website: 'https://www.undip.ac.id', majors: ['J01', 'J03', 'J04', 'J05', 'J06', 'J09', 'J10', 'J12', 'J17', 'J20'] },
  { name: 'Universitas Brawijaya', city: 'Malang', province: 'Jawa Timur', type: 'PTN', website: 'https://ub.ac.id', majors: ['J01', 'J02', 'J03', 'J04', 'J05', 'J06', 'J09', 'J10', 'J11', 'J12', 'J16', 'J20'] },
  { name: 'Universitas Sebelas Maret', city: 'Surakarta', province: 'Jawa Tengah', type: 'PTN', website: 'https://uns.ac.id', majors: ['J03', 'J04', 'J05', 'J07', 'J09', 'J12', 'J13', 'J14', 'J20'] },
  { name: 'Universitas Negeri Yogyakarta', city: 'Yogyakarta', province: 'DI Yogyakarta', type: 'PTN', website: 'https://www.uny.ac.id', majors: ['J04', 'J05', 'J07', 'J13'] },
  { name: 'BINUS University', city: 'Jakarta', province: 'DKI Jakarta', type: 'PTS', website: 'https://binus.ac.id', majors: ['J01', 'J02', 'J03', 'J04', 'J05', 'J07', 'J19'] },
  { name: 'Telkom University', city: 'Bandung', province: 'Jawa Barat', type: 'PTS', website: 'https://telkomuniversity.ac.id', majors: ['J01', 'J02', 'J04', 'J05', 'J07', 'J08'] },
  { name: 'Universitas Islam Indonesia', city: 'Yogyakarta', province: 'DI Yogyakarta', type: 'PTS', website: 'https://www.uii.ac.id', majors: ['J01', 'J03', 'J04', 'J06', 'J11', 'J12', 'J14', 'J20'] },
  { name: 'Universitas Trisakti', city: 'Jakarta', province: 'DKI Jakarta', type: 'PTS', website: 'https://trisakti.ac.id', majors: ['J03', 'J04', 'J07', 'J09', 'J12', 'J14', 'J15', 'J20'] },
  { name: 'Universitas Hasanuddin', city: 'Makassar', province: 'Sulawesi Selatan', type: 'PTN', website: 'https://unhas.ac.id', majors: ['J01', 'J03', 'J04', 'J09', 'J10', 'J11', 'J12', 'J20', 'J21', 'J24'] },
  { name: 'Universitas Andalas', city: 'Padang', province: 'Sumatera Barat', type: 'PTN', website: 'https://www.unand.ac.id', majors: ['J03', 'J04', 'J09', 'J10', 'J11', 'J12', 'J16', 'J17', 'J23', 'J24'] },
  { name: 'Universitas Sumatera Utara', city: 'Medan', province: 'Sumatera Utara', type: 'PTN', website: 'https://www.usu.ac.id', majors: ['J01', 'J03', 'J04', 'J05', 'J09', 'J10', 'J12', 'J20', 'J24', 'J28'] },
  { name: 'Universitas Pendidikan Indonesia', city: 'Bandung', province: 'Jawa Barat', type: 'PTN', website: 'https://www.upi.edu', majors: ['J05', 'J06', 'J07', 'J13', 'J18', 'J27'] },
  { name: 'Universitas Negeri Malang', city: 'Malang', province: 'Jawa Timur', type: 'PTN', website: 'https://um.ac.id', majors: ['J04', 'J05', 'J07', 'J13', 'J27', 'J28'] },
  { name: 'Universitas Jenderal Soedirman', city: 'Purwokerto', province: 'Jawa Tengah', type: 'PTN', website: 'https://unsoed.ac.id', majors: ['J03', 'J04', 'J05', 'J06', 'J10', 'J12', 'J16', 'J23', 'J24'] },
  { name: 'Universitas Negeri Semarang', city: 'Semarang', province: 'Jawa Tengah', type: 'PTN', website: 'https://unnes.ac.id', majors: ['J04', 'J05', 'J07', 'J12', 'J13', 'J23', 'J27'] },
  { name: 'Universitas Udayana', city: 'Denpasar', province: 'Bali', type: 'PTN', website: 'https://www.unud.ac.id', majors: ['J01', 'J03', 'J04', 'J09', 'J10', 'J11', 'J12', 'J20', 'J29'] },
  { name: 'Universitas Mataram', city: 'Mataram', province: 'Nusa Tenggara Barat', type: 'PTN', website: 'https://unram.ac.id', majors: ['J03', 'J04', 'J09', 'J12', 'J16', 'J17', 'J20', 'J30'] },
  { name: 'Universitas Lambung Mangkurat', city: 'Banjarmasin', province: 'Kalimantan Selatan', type: 'PTN', website: 'https://ulm.ac.id', majors: ['J01', 'J03', 'J04', 'J09', 'J10', 'J12', 'J17', 'J20', 'J30'] },
  { name: 'Universitas Mulawarman', city: 'Samarinda', province: 'Kalimantan Timur', type: 'PTN', website: 'https://unmul.ac.id', majors: ['J01', 'J03', 'J04', 'J05', 'J12', 'J16', 'J17', 'J24', 'J30'] },
  { name: 'Universitas Sam Ratulangi', city: 'Manado', province: 'Sulawesi Utara', type: 'PTN', website: 'https://www.unsrat.ac.id', majors: ['J01', 'J03', 'J04', 'J09', 'J10', 'J12', 'J16', 'J20', 'J24'] },
  { name: 'Universitas Kristen Petra', city: 'Surabaya', province: 'Jawa Timur', type: 'PTS', website: 'https://www.petra.ac.id', majors: ['J01', 'J02', 'J04', 'J05', 'J07', 'J14', 'J20', 'J25'] },
  { name: 'Universitas Atma Jaya Yogyakarta', city: 'Yogyakarta', province: 'DI Yogyakarta', type: 'PTS', website: 'https://www.uajy.ac.id', majors: ['J01', 'J03', 'J04', 'J05', 'J12', 'J14', 'J20', 'J25'] },
  { name: 'Universitas Muhammadiyah Yogyakarta', city: 'Yogyakarta', province: 'DI Yogyakarta', type: 'PTS', website: 'https://www.umy.ac.id', majors: ['J01', 'J03', 'J04', 'J05', 'J09', 'J10', 'J12', 'J18', 'J28'] },
];

export const rules = [
  { code: 'R01', name: 'Teknologi dan logika', major: 'J01', indicators: ['I02', 'I03', 'I04', 'I15'], conclusion: 'Kuat di logika, teknologi, pemrograman, dan pemecahan masalah.' },
  { code: 'R02', name: 'Data dan bisnis digital', major: 'J02', indicators: ['I03', 'I05', 'I06', 'I15'], conclusion: 'Minat teknologi, data, bisnis, dan solusi organisasi saling terhubung.' },
  { code: 'R03', name: 'Akurat dengan angka', major: 'J03', indicators: ['I07', 'I08', 'I20', 'I31'], conclusion: 'Teliti, suka angka, dan nyaman bekerja terstruktur.' },
  { code: 'R04', name: 'Strategi bisnis dan organisasi', major: 'J04', indicators: ['I06', 'I16', 'I17', 'I18'], conclusion: 'Suka bisnis, perencanaan, organisasi, dan kerja tim.' },
  { code: 'R05', name: 'Komunikasi publik', major: 'J05', indicators: ['I11', 'I12', 'I16', 'I32'], conclusion: 'Kuat di komunikasi, public speaking, media, dan kolaborasi.' },
  { code: 'R06', name: 'Empati dan perilaku manusia', major: 'J06', indicators: ['I13', 'I14', 'I11', 'I19'], conclusion: 'Suka membantu orang, tertarik perilaku manusia, dan nyaman berkomunikasi.' },
  { code: 'R07', name: 'Kreatif visual', major: 'J07', indicators: ['I09', 'I10', 'I11', 'I32'], conclusion: 'Kreatif, tertarik desain visual, komunikasi, dan media kreatif.' },
  { code: 'R08', name: 'Efisiensi dan struktur kerja', major: 'J08', indicators: ['I02', 'I15', 'I17', 'I20'], conclusion: 'Suka logika, perencanaan, proses terstruktur, dan optimasi masalah.' },
  { code: 'R09', name: 'Biomedis dan problem solving', major: 'J09', indicators: ['I13', 'I19', 'I21', 'I15'], conclusion: 'Tertarik kesehatan, riset, problem solving, dan kepedulian manusia.' },
  { code: 'R10', name: 'Perawatan pasien', major: 'J10', indicators: ['I13', 'I22', 'I11', 'I16'], conclusion: 'Suka membantu, merawat pasien, komunikasi, dan kerja tim.' },
  { code: 'R11', name: 'Kimia obat dan laboratorium', major: 'J11', indicators: ['I21', 'I23', 'I19', 'I20'], conclusion: 'Tertarik kesehatan, kimia laboratorium, riset, dan pekerjaan teliti.' },
  { code: 'R12', name: 'Argumentasi hukum', major: 'J12', indicators: ['I24', 'I11', 'I25', 'I34'], conclusion: 'Tertarik hukum, komunikasi, menulis, dan isu sosial.' },
  { code: 'R13', name: 'Mengajar dan membimbing', major: 'J13', indicators: ['I27', 'I13', 'I11', 'I17'], conclusion: 'Suka mengajar, membantu orang, komunikasi, dan perencanaan pembelajaran.' },
  { code: 'R14', name: 'Ruang dan desain bangunan', major: 'J14', indicators: ['I29', 'I10', 'I09', 'I15'], conclusion: 'Suka bangunan, desain visual, kreativitas, dan masalah ruang.' },
  { code: 'R15', name: 'Mesin dan sistem mekanik', major: 'J15', indicators: ['I28', 'I01', 'I02', 'I15'], conclusion: 'Tertarik mesin, matematika, logika, dan masalah teknis.' },
  { code: 'R16', name: 'Bisnis pertanian dan pangan', major: 'J16', indicators: ['I33', 'I06', 'I17', 'I18'], conclusion: 'Tertarik pertanian pangan, bisnis, perencanaan, dan organisasi.' },
  { code: 'R17', name: 'Lingkungan dan keberlanjutan', major: 'J17', indicators: ['I30', 'I19', 'I21', 'I34'], conclusion: 'Peduli lingkungan, suka riset, biologi, dan isu sosial.' },
  { code: 'R18', name: 'Global dan diplomasi', major: 'J18', indicators: ['I26', 'I11', 'I34', 'I19'], conclusion: 'Suka bahasa asing, komunikasi, isu sosial, dan analisis global.' },
  { code: 'R19', name: 'Statistika dan data', major: 'J19', indicators: ['I01', 'I05', 'I08', 'I19'], conclusion: 'Kuat matematika, angka, analisis data, dan riset.' },
  { code: 'R20', name: 'Struktur dan infrastruktur', major: 'J20', indicators: ['I29', 'I01', 'I20', 'I15'], conclusion: 'Suka bangunan, matematika, struktur kerja, dan masalah konstruksi.' },
  { code: 'R21', name: 'Keamanan digital', major: 'J01', indicators: ['I36', 'I02', 'I03', 'I04'], conclusion: 'Minat keamanan digital mengarah kuat ke informatika.' },
  { code: 'R22', name: 'Produk digital bisnis', major: 'J02', indicators: ['I03', 'I05', 'I06', 'I17'], conclusion: 'Mampu menghubungkan teknologi, data, bisnis, dan perencanaan produk.' },
  { code: 'R23', name: 'Media dan penulisan', major: 'J05', indicators: ['I11', 'I12', 'I25', 'I32'], conclusion: 'Kuat di komunikasi, menulis, media kreatif, dan public speaking.' },
  { code: 'R24', name: 'Keuangan analitis', major: 'J03', indicators: ['I31', 'I08', 'I07', 'I05'], conclusion: 'Tertarik keuangan, angka, ketelitian, dan analisis data.' },
  { code: 'R25', name: 'Kelistrikan dan sistem kontrol', major: 'J21', indicators: ['I01', 'I02', 'I03', 'I28'], conclusion: 'Kuat di matematika, logika, teknologi, dan sistem peralatan.' },
  { code: 'R26', name: 'Proses kimia industri', major: 'J22', indicators: ['I01', 'I20', 'I23', 'I28'], conclusion: 'Cocok dengan proses industri, kimia, ketelitian, dan sistem teknis.' },
  { code: 'R27', name: 'Gizi dan kesehatan', major: 'J23', indicators: ['I13', 'I21', 'I22', 'I23'], conclusion: 'Tertarik kesehatan, perawatan, biologi, dan kebutuhan gizi manusia.' },
  { code: 'R28', name: 'Program kesehatan publik', major: 'J24', indicators: ['I13', 'I19', 'I21', 'I34'], conclusion: 'Peduli kesehatan, riset, masyarakat, dan isu sosial.' },
  { code: 'R29', name: 'Operasional bisnis', major: 'J25', indicators: ['I06', 'I16', 'I17', 'I20'], conclusion: 'Suka bisnis, kerja tim, perencanaan, dan pekerjaan terstruktur.' },
  { code: 'R30', name: 'Analisis ekonomi dan kebijakan', major: 'J26', indicators: ['I05', 'I19', 'I31', 'I34'], conclusion: 'Kuat di data, riset, ekonomi, dan isu kebijakan publik.' },
  { code: 'R31', name: 'Bahasa dan komunikasi global', major: 'J27', indicators: ['I11', 'I25', 'I26', 'I34'], conclusion: 'Suka bahasa, menulis, komunikasi, dan konteks sosial budaya.' },
  { code: 'R32', name: 'Politik dan kebijakan', major: 'J28', indicators: ['I11', 'I19', 'I24', 'I34'], conclusion: 'Tertarik komunikasi, riset, hukum, dan isu sosial politik.' },
  { code: 'R33', name: 'Kota dan tata wilayah', major: 'J29', indicators: ['I17', 'I29', 'I30', 'I35'], conclusion: 'Suka perencanaan, ruang, lingkungan, peta, dan wilayah.' },
  { code: 'R34', name: 'Teknologi pengelolaan lingkungan', major: 'J30', indicators: ['I15', 'I20', 'I28', 'I30'], conclusion: 'Cocok dengan masalah teknis, sistem kerja, peralatan, dan lingkungan.' },
];
